include '../inc/notes.inc'

dw G3, CONT, REST, REST, D4, CONT, B3, CONT, B3, CONT, REST, REST, A3, CONT, G3, CONT, G3, CONT, C4, CONT, REST, REST, B3, CONT, B3, CONT, A3, CONT, A3, CONT, G3, CONT, REST, REST, G3, CONT, D4, CONT, B3, CONT, B3, CONT, A3, CONT, A3, CONT, G3, CONT, G3, CONT, E3, CONT, CONT, CONT, D3, CONT, CONT, CONT, CONT, CONT, CONT, ENDS